name: .NET 5 CI
'on':
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    name: .NET 5 Application
    steps:
      - uses: actions/checkout@v2
      - name: Setup-dotnet
      - uses: Setup-dotnet@v1
        with:
          dotnet-version: 5.0.401
      - name: Restore Dependencies
        run: dotnet restore
      - name: build Application
        run: dotnet build -c release --no--restore